//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuVQuiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataInsertion
    {
        public int questionID { get; set; }
        public int? companyID { get; set; }
        public string options { get; set; }
    }
}
